export interface ThemeConfig {
  id: string;
  name: string;
  bg: string;
  titleFont: string;
  titleColor: string;
  titleWeight: string;
  bodyFont: string;
  bodyColor: string;
  bodyWeight: string;
  tagBg: string;
  tagColor: string;
  tagRadius: number;
  tagBorder: string;
  cardRadius: number;
  cardBorder: string;
  cardShadow: string;
  shadowBlur?: number;
  shadowOffsetY?: number;
}

export const THEMES: Record<string, ThemeConfig> = {
  apple: {
    id: 'apple',
    name: 'Apple',
    bg: '#1C1C1E',
    titleFont: 'Inter, sans-serif',
    titleColor: '#FFFFFF',
    titleWeight: '800',
    bodyFont: 'Inter, sans-serif',
    bodyColor: '#A1A1A6',
    bodyWeight: '300',
    tagBg: 'rgba(255,255,255,0.1)',
    tagColor: '#FFFFFF',
    tagRadius: 12,
    tagBorder: 'rgba(255,255,255,0.2)',
    cardRadius: 32,
    cardBorder: 'rgba(255,255,255,0.1)',
    cardShadow: 'transparent',
  },
  google: {
    id: 'google',
    name: 'Google',
    bg: '#F8F9FA',
    titleFont: 'Outfit, sans-serif',
    titleColor: '#202124',
    titleWeight: '600',
    bodyFont: 'Outfit, sans-serif',
    bodyColor: '#5F6368',
    bodyWeight: '400',
    tagBg: '#E8F0FE',
    tagColor: '#1967D2',
    tagRadius: 999,
    tagBorder: 'transparent',
    cardRadius: 24,
    cardBorder: 'transparent',
    cardShadow: 'rgba(0,0,0,0.08)',
    shadowBlur: 24,
    shadowOffsetY: 12,
  },
  openai: {
    id: 'openai',
    name: 'OpenAI',
    bg: '#000000',
    titleFont: 'Merriweather, serif',
    titleColor: '#FFFFFF',
    titleWeight: '700',
    bodyFont: 'Inter, sans-serif',
    bodyColor: '#D1D5DB',
    bodyWeight: '400',
    tagBg: '#10A37F',
    tagColor: '#FFFFFF',
    tagRadius: 0,
    tagBorder: 'transparent',
    cardRadius: 0,
    cardBorder: '#10A37F',
    cardShadow: 'transparent',
  },
  claude: {
    id: 'claude',
    name: 'Claude',
    bg: '#FDFBF7',
    titleFont: 'Noto Serif, serif',
    titleColor: '#2D2926',
    titleWeight: '600',
    bodyFont: 'Noto Serif, serif',
    bodyColor: '#4A4440',
    bodyWeight: '400',
    tagBg: '#EFEBE4',
    tagColor: '#4A4440',
    tagRadius: 4,
    tagBorder: '#D5D0C8',
    cardRadius: 8,
    cardBorder: '#E5E0D8',
    cardShadow: 'transparent',
  },
  grok: {
    id: 'grok',
    name: 'Grok',
    bg: '#050505',
    titleFont: 'JetBrains Mono, monospace',
    titleColor: '#FFFFFF',
    titleWeight: '700',
    bodyFont: 'JetBrains Mono, monospace',
    bodyColor: '#A3A3A3',
    bodyWeight: '400',
    tagBg: '#000000',
    tagColor: '#00FF41',
    tagRadius: 0,
    tagBorder: '#00FF41',
    cardRadius: 0,
    cardBorder: '#333333',
    cardShadow: '#00FF41',
    shadowBlur: 10,
    shadowOffsetY: 0,
  },
  meta: {
    id: 'meta',
    name: 'Meta',
    bg: '#FFFFFF',
    titleFont: 'Inter, sans-serif',
    titleColor: '#000000',
    titleWeight: '600',
    bodyFont: 'Inter, sans-serif',
    bodyColor: '#65676B',
    bodyWeight: '400',
    tagBg: '#F0F2F5',
    tagColor: '#050505',
    tagRadius: 6,
    tagBorder: 'transparent',
    cardRadius: 12,
    cardBorder: '#E5E5E5',
    cardShadow: 'transparent',
  },
  ide: {
    id: 'ide',
    name: 'Modern IDE',
    bg: '#0D1117',
    titleFont: 'JetBrains Mono, monospace',
    titleColor: '#E6EDF3',
    titleWeight: '700',
    bodyFont: 'Inter, sans-serif',
    bodyColor: '#C9D1D9',
    bodyWeight: '400',
    tagBg: 'rgba(56, 139, 253, 0.15)',
    tagColor: '#58A6FF',
    tagRadius: 4,
    tagBorder: 'rgba(56, 139, 253, 0.4)',
    cardRadius: 6,
    cardBorder: '#30363D',
    cardShadow: 'rgba(0,0,0,0.5)',
    shadowBlur: 20,
  },
  swiss: {
    id: 'swiss',
    name: 'Swiss Style',
    bg: '#F4F4F0',
    titleFont: 'Inter, sans-serif',
    titleColor: '#000000',
    titleWeight: '900',
    bodyFont: 'Inter, sans-serif',
    bodyColor: '#000000',
    bodyWeight: '500',
    tagBg: 'transparent',
    tagColor: '#FF0000',
    tagRadius: 0,
    tagBorder: 'transparent',
    cardRadius: 0,
    cardBorder: 'transparent',
    cardShadow: 'transparent',
  },
  crypto: {
    id: 'crypto',
    name: 'Web4.0 Ledger',
    bg: '#050505',
    titleFont: 'JetBrains Mono, monospace',
    titleColor: '#E0E0E0',
    titleWeight: '600',
    bodyFont: 'JetBrains Mono, monospace',
    bodyColor: '#888888',
    bodyWeight: '400',
    tagBg: '#111111',
    tagColor: '#00FF41',
    tagRadius: 2,
    tagBorder: '#333333',
    cardRadius: 2,
    cardBorder: '#333333',
    cardShadow: 'transparent',
  },
  blueprint: {
    id: 'blueprint',
    name: 'Blueprint',
    bg: '#002FA7',
    titleFont: 'Inter, sans-serif',
    titleColor: '#FFFFFF',
    titleWeight: '600',
    bodyFont: 'Inter, sans-serif',
    bodyColor: 'rgba(255,255,255,0.9)',
    bodyWeight: '400',
    tagBg: 'rgba(255,255,255,0.1)',
    tagColor: '#FFFFFF',
    tagRadius: 0,
    tagBorder: '#FFFFFF',
    cardRadius: 0,
    cardBorder: '#FFFFFF',
    cardShadow: 'transparent',
  },
  pixel: {
    id: 'pixel',
    name: 'Pixel Construct',
    bg: '#1A1A2E',
    titleFont: '"Press Start 2P", cursive',
    titleColor: '#00FFC2',
    titleWeight: '400',
    bodyFont: '"Roboto Mono", monospace',
    bodyColor: '#E0E0E0',
    bodyWeight: '400',
    tagBg: '#FF00FF',
    tagColor: '#FFFFFF',
    tagRadius: 0,
    tagBorder: '#00FFC2',
    cardRadius: 0,
    cardBorder: '#00FFC2',
    cardShadow: 'transparent',
  }
};
